### ISSUE TITLE
WSD в Питере 2015

### ISSUE THREAD

**Issue by pepelsbey** [web-standards-ru/web-standards-days#100]
# Площадка

- [x] Найти фотографа на целый день (cofemiss@)
- [ ] Найти оператора на целый день
- [x] Договориться с кормильцами: Буше, Даблби, либо пицца
- [x] Съездить на площадку и посмотреть ещё раз всё в живую
- [ ] Подобрать плейлист бодрящей музыки
- [x] Найти место для камеры с двумя розетками и езернетом
- [x] Найти волонтёров: 2 на регистрацию, 2 на микрофоны
- [ ] Вставить логотип площадки на видео
- [x] Уточнить, можно ли подключиться по HDMI к телевизору на регистрации
- [x] Забронировать бар для афтепати
- [ ] Привезти и установить столы для наклеек и книг
- [ ] Принести пилоты и удлинители, кто сколько сможет

# Печатные материалы
- [x] Сделать макеты и напечатать два баннера (2,5 м на 75 см)
- [ ] Сделать макеты и напечатать указатели (4 штуки, A4)
- [x] Подготовить и заказать наклейки
- [x] Подготовить и напечатать бейджи, нумерацию и списки

# Соцмедиа

- [x] Опубликовать видео Брюса
- [x] Опубликовать видео Юли
- [x] Опубликовать видео Вадима
- [x] Опубликовать видео Вари
- [x] Опубликовать видео Антона Виноградова
- [x] Опубликовать видео Антона Шувалова
- [x] Опубликовать видео Ромы Комарова
- [x] Опубликовать видео Василики
- [x] Опубликовать видео Олега
- [x] Разослать напоминание о конференции
- [ ] Подготовить форму для отзывов
- [ ] Подготовить и зарядить твиты с презентациями
- [ ] Объявить про вопросы на трансляции «задавайте, мы передадим» 

# Доклады

## @pepelsbey

- [ ] Скотч
- [x] Прогнать Василику Климову
- [x] Прогнать Олега Мохова
- [ ] Прогнать Рому Комарова
- [x] Прогнать Варю Степанову

## @miripiruni 
- [x] Маркеры
- [ ] Микрофоны  
- [x] Прогнать Славу Шебанова
- [x] Прогнать Антона Шувалова

# Личная занятость

## @miripiruni

- Вступительное слово
- Текстовая трансляция
- Контроль по звука

## @pepelsbey

- Первый доклад
- Таймер, слайды, докладчики
- Камера и трансляция

## @meritt

- Еда на площадке, места в округе
- Эникейщик

**Comment by miripiruni** [comment]
> Найти телевизор с HDMI для зала

Удаляю. Такой возможности на площадке нет.

**Comment by miripiruni** [comment]
Создал секцию про печатные материалы.

**Comment by h4** [comment]
@pepelsbey проверь, что отсюда ничего не нужно сохранить куда-нибудь в документы и закрой Issue, пожалуйста

**Comment by pepelsbey** [comment]
@h4, закрыл, она никуда не денется
