### ISSUE TITLE
Вычитать сабы для Брюса

### ISSUE THREAD

**Issue by pepelsbey** [web-standards-ru/web-standards-days#101]
# Английские

Hello Russia! Fancy seeing you here in Birmingham UK. It’s where I live; I’m Bruce Lawson, from Opera, the web browser that the queen uses.

Anyway, this building here is the hotel where Karl Marx wrote his final and most popular book “Harry Potter and the dictatorship of the proletariat” and that building over there is a monument to the day when we finally hanged all the modern architects.

Oh, look at the time! It’s 7 in the morning — breakfast time! Come with me.

[pub sign: The Old Crown, est. 1362]

Obviously, everyone in England drinks beer for breakfast, not water, because water is basically fish’s toilets. But we take it very slowly. Cheers!

[3 seconds later]

So anyway, I’m coming to St. Petersburg for Web Standards Days on June 20th, and I’m going to be talking about “Is Blink the new IE6?”. What does that mean, Bruce? Well…

So the question is — is Blink, the rendering engine that’s in Opera and Chromium, turning into a monopoly in the same way that Internet Explorer 6 did? Come to Web Standards Days in St. Petersburg on June 20th to find out.

# Русские

Привет, Россия! Рад видеть вас в Англии, в Бирмингеме. Здесь я живу. Я Брюс Лоусон из Opera — браузера, которым пользуется королева.

Как бы там ни было, это здание — гостиница, в котором Карл Маркс написал свою последнюю и самую популярную книгу «Гарри Поттер и Диктатура пролетариата». А вон то здание за ней — это памятник дню, когда мы наконец-то повесим всех современных архитекторов.

О, посмотрите на время! Семь утра — время завтракать! Пойдёмте со мной.

[надпись на пабе: The Old Crown, осн. 1362]

Конечно же, в Англии все пьют на завтрак пиво, а не воду, ведь вода, по сути — рыбий туалет. Но мы пьем медленно. Ваше здоровье!

[Три секунды спустя]

Ну так вот, я приезжаю в Санкт-Петербург на Web Standards Days 20-го июня и собираюсь рассказать, «Почему Blink — это не новый IE6». Что же это значит, Брюс? Хорошо…

Итак, вопрос следующий: не становится ли Blink, движок в основе Opera и Chromium, монополией — так же, как когда-то Internet Explorer 6? Приходите на Web Standards Days в Санкт-Петербурге 20-го июня и узнаете.

**Comment by pepelsbey** [comment]
Можно отредактировать прямо текст таски.

**Comment by tachisis** [comment]
Отредактировала русский вариант.

**Comment by pepelsbey** [comment]
Данкешён!
