### ISSUE TITLE
Настроить nginx

### ISSUE THREAD

**Issue by pepelsbey** [web-standards-ru/web-standards-days#108]
PageSpeed Insights показывает [плохие вещи](https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Fwsd.events%2F&tab=mobile): 40 и 60 на мобильном и десктопе. Нет ни `gzip`, ни `expiration`. Взять, например, [h5bp/server-configs-nginx](https://github.com/h5bp/server-configs-nginx) и применить.

**Comment by h4** [comment]
83/100 и 93/100

Но меня очень беспокоит тот факт, что у нас нет меток для инвалидации кеша статики.

**Comment by pepelsbey** [comment]
@h4, а это отдельная таска :) У меня почему-то 55-66 сейчас, откуда 83-93?

**Comment by h4** [comment]
А фиг знает, теперь у меня тоже стало поменьше.

**Comment by pepelsbey** [comment]
Окей, главное что есть `gzip` и `expire`, а оптимизацией можно заняться отдельно.

Спасибо!

**Comment by h4** [comment]
Просто там в h5bp экспайр большой стоит, так что надо думать, да.
