### ISSUE TITLE
Список докладов

### ISSUE THREAD

**Issue by greybax** [web-standards-ru/web-standards-days#114]
Сделайте пожалуйста список докладов, со ссылкой на их описание ниже в "Программе". Сейчас выглядит не очень удобно и не наглядно какие доклады представлены на конференции, приходится скроллить весь список вниз

**Comment by pepelsbey** [comment]
Мы хотели избежать дублирования, поскольку список докладов — это, по сути, и есть программа. Возможно, стоит сворачивать описания докладов или прятать их на фиксированную высоту. Как-то так?

**Comment by greybax** [comment]
> стоит сворачивать описания докладов 

:+1:

**Comment by h4** [comment]
А потому нужно будет разворачивать их?

**Comment by greybax** [comment]
думаю для наглядности полного списка докладов было бы удобно показывать просто только названия, а по клике на названии уже его разворачивать

**Comment by h4** [comment]
Не уверен, что такой вариант добавить наглядности (см. скриншот). По названиям доклада далеко не всегда понятно, о чём в нём будет идти речь 

![image](https://cloud.githubusercontent.com/assets/430023/11207318/a013d582-8d25-11e5-82d3-edfd604f77f3.png)

**Comment by h4** [comment]
Не спорю, что есть ситуации, когда хочется сжатого представления списка докладов. Но, на мой взгляд, это не должно быть основным представлением.

**Comment by greybax** [comment]
возможно еще бы подошел вариант как список (оглавление) всех докладов вверху страницы и переход на их описание по якорям

**Comment by pepelsbey** [comment]
Да, видимо оглавление будет лучше, попробую что-нибудь набросать.
