### ISSUE TITLE
Заголовки для безопасности

### ISSUE THREAD

**Issue by pepelsbey** [web-standards-ru/web-standards-days#115]
- [x] MISSING Referrer-Policy
- [x] MISSING Content-Security-Policy
- [x] MISSING X-Frame-Options
- [x] MISSING X-Xss-Protection
- [x] MISSING X-Content-Type-Options

[SecurityHeaders.io — wsd.events](https://securityheaders.io/?q=https%3A%2F%2Fwsd.events)

**Comment by h4** [comment]
Ок, добавлю. Хотел спросить — что это за фигня вообще, а там по ссылке всё разжевано. Молодцы ребята.

**Comment by h4** [comment]
На паузе, пока с сертификатом нормально не разберёмся.

**Comment by h4** [comment]
Там nginx стал как-то странно перезапускаться, пока что опасаюсь править конфиги, чтобы всё не разломать.

**Comment by jahson** [comment]
C nginx это я накосячил как-то, всё никак не пойму, как. Пока что конфиги можно перезагружать через `sudo nxing -s reload`.

- [ ] Content-Security-Policy
- [x] X-Frame-Options
- [x] X-Xss-Protection
- [x] X-Content-Type-Options

С `CSP` там целая отдельная история и нужно решить, какова политика партии.

**Comment by jahson** [comment]
А вот кажется и [про наш nginx](https://bugs.launchpad.net/nginx/+bug/1476296).

**Comment by pepelsbey** [comment]
[Уточнил ссылку](https://securityheaders.io/?q=https%3A%2F%2Fwsd.events), теперь с HTTPS.

**Comment by pepelsbey** [comment]
Осталось 2 заголовка. Кто-нибудь поможет добить CSP и Referrer-Policy?

**Comment by h4** [comment]
Довёл до [A-Grade](https://securityheaders.io/?q=https%3A%2F%2Fwsd.events). A+ не получается из-за необходимости включать 'unsafe-inline' 'unsafe-eval' для того, чтобы всё работало (какие-то из подключённых скриптов) этого хотят.

**Comment by pepelsbey** [comment]
Крутой! Спасибо :)

**Comment by h4** [comment]
@pepelsbey будет время — посмотри, не отвалилось ли что в передаче данных в метрике. Ну и весь сайт было бы неплохо прокликать с открытой консолью.

**Comment by pepelsbey** [comment]
Для Киева грузим Google Maps, надо их добавить в CSP, см. https://wsd.events/2017/11/04/

**Comment by h4** [comment]
Fixed.

**Comment by pepelsbey** [comment]
Спасибо!
