### ISSUE TITLE
Артефакты при отображении текста

### ISSUE THREAD

**Issue by solar-vibez** [web-standards-ru/web-standards-days#144]
Вот [по этой ссылке](https://wsd.events/2017/10/21/#schedule) странно отображается текст:
![image](https://user-images.githubusercontent.com/1024344/31537865-4a560b2c-b00c-11e7-941b-6ef44e497f92.png)

ОS: Windows 10 
Browser: Chrome Version 61.0.3163.100 (Official Build) (64-bit)

При замене в dev tools на шрифт, например, `font-family: sans-serif`, все отображается без артефактов.
Кажется, что-то не то с отображением шрифта "Ubuntu"...
![image](https://user-images.githubusercontent.com/1024344/31538127-38b4484c-b00d-11e7-9a05-4e37fc688477.png)

**Comment by GreLI** [comment]
Аналогично, ничего не поменялось. Если вставить
```html
<link href="https://fonts.googleapis.com/css?family=Ubuntu:400,500&amp;subset=cyrillic" rel="stylesheet">
```
то всё становится нромально.

Шрифт с сайта https://wsd.events/fonts/ubuntu-regular-latin.woff2 весит 13,4 КБ и в нём явно отсутствует хинтинг. Шрифт с Google Fonts (https://fonts.gstatic.com/s/ubuntu/v11/4iCs6KVjbNBYlgoKfw72.woff2) весит 33,5 КБ и рендерится заметно чётче даже в окошке предпросмотра девтулзов. Если шрифт брался с Google Fonts, то может сервис отдает на маке облегчённую версию без хинтинга?

**Comment by pepelsbey** [comment]
Похоже на то :(

Сейчас сделаю руками шрифты из TTF, подключу и проверим снова.

**Comment by pepelsbey** [comment]
Запросил шрифты в Edge и IE11 по ссылке https://fonts.googleapis.com/css?family=Ubuntu:400,400i,500,700&subset=cyrillic и сейчас деплою версию с WOFF и WOFF2, с хинтингом. Шрифты теперь весят по 40—50 КБ.

**Comment by GreLI** [comment]
Стало лучше! (Хотя, похоже, что шрифт Ubuntu не очень оптимизирован: например, у буквы «к» толстые ножки, а у «M» тонкие перекладинки.)

**Comment by solar-vibez** [comment]
Артефакты исчезли, может закрыть? Проблема-то пофикшена :)

**Comment by pepelsbey** [comment]
Да, всем спасибо :) Шрифты стали тяжелее, но чётче.
