### ISSUE TITLE
Апнуть Node.js и npm для Travis CI

### ISSUE THREAD

**Issue by pepelsbey** [web-standards-ru/web-standards-days#146]
Собственно, сабж. Это, по идее, должно ускорить сборку. Кажется это вопрос изменения [циферки в конфиге](https://github.com/web-standards-ru/web-standards-days/blob/master/.travis.yml#L5), но я могу ошибаться.

@h4, что думаешь?

**Comment by h4** [comment]
До восьмёрки?

**Comment by pepelsbey** [comment]
А чего бы и нет.

**Comment by h4** [comment]
Вообще, можно было бы выставить 
```yaml
node_js:
- 'lts/*'
```
но восьмая нода станет LTS только через две недели
