### ISSUE TITLE
Отсортировать докладчиков на главной по появлению

### ISSUE THREAD

**Issue by pepelsbey** [web-standards-ru/web-standards-days#148]
Сейчас у нас докладчики в списке на главной отсортированы по фамилии в алфавитном порядке. И получается, что первый блок из 20 человек набился счастливчиками на `А-`, а хотелось бы показывать там новые лица. Отсюда задача:

1. Пройтись по программам всех лет, начиная с 2009.
2. Собрать список докладчиков по времени их появления на сцене.
3. Обновить сортировку на главной соответственно.

Вряд ли это как-то особенно автоматизируется, вопрос одного вечера и пулреквеста.

**Comment by IgorLesnevskiy** [comment]
а если человек участвовал в нескольких конференциях в разные годы? ставить его в порядке самого последнего выступления?

**Comment by pepelsbey** [comment]
Порядок один: первое появление на WSD. Последующие не считаются :)

**Comment by IgorLesnevskiy** [comment]
т.е. те, кто появился позже, будут показываться выше? например, новые люди с текущей конфы будут на самом верху?

**Comment by pepelsbey** [comment]
Да, всё верно: первым в списке будет Павел Никитюк (закрывает Киев, 2017), последним Андрей Сумин (открывал Минск, 2009). Все новые докладчики будут просто добавляться в начало списка.

**Comment by IgorLesnevskiy** [comment]
сегодня вечером - завтра утром сделаю

**Comment by pepelsbey** [comment]
Сделано в #149, ещё раз всем спасибо :)
