### ISSUE TITLE
Сделать сворачивалку календаря на главной

### ISSUE THREAD

**Issue by pepelsbey** [web-standards-ru/web-standards-days#153]
Сейчас календарь слишком длинный и хорошо было бы к нему снизу сделать кнопку «Показать весь», которая появляется после последних трёх лет и разворачивает остальной календарь. Требования:

— Кнопка `<button>`, доступная с клавиатуры
— Можно свернуть обратно
— Сворачивание-разворачивание понятно скринридерам

Над дизайном ещё подумаем, но пока можно использовать:

```html
<button class="button button--full">Показать весь</button>
```

**Comment by tsergeytovarov** [comment]
А может ещё добавить разделение на года? Какую-то вставку, которая могла бы обозначать год.

**Comment by pepelsbey** [comment]
Так справа же?

![image](https://user-images.githubusercontent.com/105274/35501732-cc0f4bea-04eb-11e8-94db-b56b605fbc53.png)

**Comment by tsergeytovarov** [comment]
Точно. Не заметил)

**Comment by pepelsbey** [comment]
Fixed :)
