### ISSUE TITLE
Добавить внятный CSP

### ISSUE THREAD

**Issue by pepelsbey** [web-standards-ru/web-standards-days#158]
Пока отключил CSP, он даёт ошибки. [Положил конфиг](https://github.com/web-standards-ru/web-standards-days/blob/master/csp.conf) в репозиторий. Там, кроме обычных мер безопасности, нужно учесть из внешнего:

- Ютуб
- Гугл Карты
- Яндекс Карты

Вот, например, [руководство по CSP от Яндекс Карт](https://tech.yandex.ru/maps/doc/jsapi/2.1/dg/concepts/load-docpage/#load__using-csp).

Будет исправлено в https://github.com/web-standards-ru/web-standards-days/pull/164

**Comment by pepelsbey** [comment]
@alexbaumgertner, велком, если интересно :)

**Comment by alexbaumgertner** [comment]
Ок!

Набросал черновик списка доменов, куда нужно открыть доступ:
1. https://www.youtube.com/
1. https://*.googlevideo.com/videoplayback
1. https://i.ytimg.com/
1. https://static.doubleclick.net/
1. https://www.google.com/js/
1. https://googleads.g.doubleclick.net/
1. https://mc.yandex.ru/
1. https://img.youtube.com/
1. https://api-maps.yandex.ru/
1. https://*.maps.yandex.net/tiles

Посмотрю в https://www.w3.org/TR/CSP/
В секции "[External_links](https://en.wikipedia.org/wiki/Content_Security_Policy#External_links)" wiki-странички есть инструменты для генерации CSP.
