### ISSUE TITLE
wsd.events блокируется McAfee

### ISSUE THREAD

**Issue by dmitry-korolev** [web-standards-ru/web-standards-days#175]
Линк: https://www.siteadvisor.com/sitereport.html?url=wsd.events

**Comment by pepelsbey** [comment]
Есть идеи, что можно с этим сделать?

**Comment by FFxSquall** [comment]
Я пробежался по скриптам подключеным, но не вижу пока ни одной причины. Сейчас там только код для подключения карт и видео с ютьюбчика. Может, что-то раньше было и McAfee давно проверку не делал. Можно ему сообщить, что теперь с сайтом всё ок или перепроверку запросить?

**Comment by pepelsbey** [comment]
Напишу письмо, спасибо!

**Comment by dmitry-korolev** [comment]
![image](https://user-images.githubusercontent.com/12699282/54433379-c332b180-473c-11e9-8711-16528c3e65a2.png)
Оперативно =)
