### ISSUE TITLE
Прочистить репозиторий

### ISSUE THREAD

**Issue by h4** [web-standards-ru/web-standards-days#19]
Сейчас, когда делаешь `git clone git@github.com:web-standards-ru/web-standards-days.git` к тебе приезжает 104.62 MiB, что несколько до фига.

Причина — мы удалили презентации и прочую тяжеляку из **working copy**, но не из `.git/objects`

Решение этой проблемы есть, но для него придётся полностью перезалить репозиторий, что может привести к конфликтам у тех, кто давно его вытянул и потом попробует что-то влить обратно.

**Comment by pepelsbey** [comment]
@h4, ветка `new` начата «сиротой», поэтому всё должно быть нормально с тяжестями. Так ведь? Я правда ещё не придумал, как она вольётся в `master` (или заменит его).

**Comment by h4** [comment]
Неа. Не так. Весь мусор хранится в чанках в `.git`. Поэтому всё равно надо будет делать filter-branch.

**Comment by h4** [comment]
Алиллушеньки, закрываем!
